const testData = [
  {
    login: 'lauritsen',
    id: 17593128,
    node_id: 'MDQ6VXNlcjE3NTkzMTI4',
    avatar_url: 'https://avatars.githubusercontent.com/u/17593128?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/lauritsen',
    html_url: 'https://github.com/lauritsen',
    followers_url: 'https://api.github.com/users/lauritsen/followers',
    following_url:
      'https://api.github.com/users/lauritsen/following{/other_user}',
    gists_url: 'https://api.github.com/users/lauritsen/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/lauritsen/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/lauritsen/subscriptions',
    organizations_url: 'https://api.github.com/users/lauritsen/orgs',
    repos_url: 'https://api.github.com/users/lauritsen/repos',
    events_url: 'https://api.github.com/users/lauritsen/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/lauritsen/received_events',
    type: 'User',
    site_admin: false,
    name: 'Henrik Lauritsen',
    company: null,
    blog: '',
    location: 'Aarhus, Denmark',
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 9,
    public_gists: 0,
    followers: 1,
    following: 2,
    created_at: '2016-03-02T12:37:36Z',
    updated_at: '2021-02-20T14:28:38Z',
  },
  {
    login: 'skovhus',
    id: 1260305,
    node_id: 'MDQ6VXNlcjEyNjAzMDU=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1260305?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/skovhus',
    html_url: 'https://github.com/skovhus',
    followers_url: 'https://api.github.com/users/skovhus/followers',
    following_url:
      'https://api.github.com/users/skovhus/following{/other_user}',
    gists_url: 'https://api.github.com/users/skovhus/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/skovhus/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/skovhus/subscriptions',
    organizations_url: 'https://api.github.com/users/skovhus/orgs',
    repos_url: 'https://api.github.com/users/skovhus/repos',
    events_url: 'https://api.github.com/users/skovhus/events{/privacy}',
    received_events_url: 'https://api.github.com/users/skovhus/received_events',
    type: 'User',
    site_admin: false,
    name: 'Kenneth Skovhus',
    company: '@tmrowco',
    blog: 'https://skovhus.github.io/',
    location: 'Copenhagen, Denmark',
    email: null,
    hireable: null,
    bio: null,
    twitter_username: 'kenneth_skovhus',
    public_repos: 80,
    public_gists: 11,
    followers: 60,
    following: 39,
    created_at: '2011-12-13T13:27:43Z',
    updated_at: '2021-02-18T13:05:51Z',
  },
];

export default testData;
